spring:
  batch:
    job:
      enabled: true
      name: tickerSlackJob
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/crypto-notification'
    username: root
    password: Java2023@#
  sql:
    init:
      mode: never

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true