spring:
    datasource:
      driver-class-name: org.h2.Driver
      url: 'jdbc:h2:mem:testdb;MODE=MYSQL'
      username: sa
    sql:
      init:
        mode: always

#'jdbc:mysql://localhost:3306/crypto-notification'